### ISSUE TITLE
Automatic Install and Load of RobStatTM and fit.models

### ISSUE THREAD

**Issue by martinrd3D** [jaindhairyahere/PerformanceAnalytics#9]
The packages RobStatTM and fit.models need to be installed and loaded to use the SFM and the SFM.fit.models functions, respectively.  How will this be implemented?  However it is implemented, the capability needs to be mentioned in the manual/help files

If the user does not have either of those two packages, and uses SFM or SFM.fit.models (assuming we keep this function), an automatic check will give the user a Warning, saying that the package will be automatically installed and loaded, subject to the user responding that it is ok.

NOTE:  Currently the examples require the user to have installed and loaded RobStatTM for SFM and fit.models for SFM.fit.models

### Minimal, reproducible example

```r
[Insert sample data and code]
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by jaindhairyahere** [comment]
I think this has been resolved
